// File generated by FlutterFire CLI template.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with Firebase services across Web, Android, iOS, and desktop.
///
/// To configure for your specific Firebase project, install the FlutterFire CLI:
///   dart pub global activate flutterfire_cli
///   flutterfire configure
class DefaultFirebaseOptions {
  /// Whether real (non-placeholder) Firebase project credentials are provided.
  static bool get isConfigured =>
      web.apiKey != 'AIzaSyPlaceholderWebApiKeyForRecipetools' &&
      web.projectId != 'recipetools-placeholder';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG5zGoSlSwStPE-MxY33r0hZMeng28PcI',
    appId: '1:194514517992:web:c03bc87d5fe1ce309bae5d',
    messagingSenderId: '194514517992',
    projectId: 'chefycost',
    authDomain: 'chefycost.firebaseapp.com',
    storageBucket: 'chefycost.firebasestorage.app',
    measurementId: 'G-24JWL09P82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLpYuok3dJhDJ7k4gOhL5pBeD1YgJ_ubU',
    appId: '1:194514517992:android:e049ba4d67978ff89bae5d',
    messagingSenderId: '194514517992',
    projectId: 'chefycost',
    storageBucket: 'chefycost.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJHjHLEqqsPKQI2joDupFBWJFXcztaFn4',
    appId: '1:194514517992:ios:635a898ca8c7658e9bae5d',
    messagingSenderId: '194514517992',
    projectId: 'chefycost',
    storageBucket: 'chefycost.firebasestorage.app',
    iosBundleId: 'com.example.recipetools',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJHjHLEqqsPKQI2joDupFBWJFXcztaFn4',
    appId: '1:194514517992:ios:635a898ca8c7658e9bae5d',
    messagingSenderId: '194514517992',
    projectId: 'chefycost',
    storageBucket: 'chefycost.firebasestorage.app',
    iosBundleId: 'com.example.recipetools',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG5zGoSlSwStPE-MxY33r0hZMeng28PcI',
    appId: '1:194514517992:web:4c80178f12dd20069bae5d',
    messagingSenderId: '194514517992',
    projectId: 'chefycost',
    authDomain: 'chefycost.firebaseapp.com',
    storageBucket: 'chefycost.firebasestorage.app',
    measurementId: 'G-H29Z1CV5N3',
  );
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_LINUX_API_KEY',
        defaultValue: 'AIzaSyPlaceholderLinuxApiKey'),
    appId: String.fromEnvironment('FIREBASE_LINUX_APP_ID',
        defaultValue: '1:1234567890:web:abcdef123456'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '1234567890'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'recipetools-placeholder'),
    authDomain: 'recipetools-placeholder.firebaseapp.com',
    storageBucket: 'recipetools-placeholder.firebasestorage.app',
  );
}
