// File generated by FlutterFire CLI template.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with Firebase services across Web, Android, iOS, and desktop.
///
/// To configure for your specific Firebase project, install the FlutterFire CLI:
///   dart pub global activate flutterfire_cli
///   flutterfire configure
class DefaultFirebaseOptions {
  /// Whether real (non-placeholder) Firebase project credentials are provided.
  static bool get isConfigured =>
      web.apiKey != 'AIzaSyPlaceholderWebApiKeyForRecipetools' &&
      web.projectId != 'recipetools-placeholder';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY',
        defaultValue: 'AIzaSyPlaceholderWebApiKeyForRecipetools'),
    appId: String.fromEnvironment('FIREBASE_WEB_APP_ID',
        defaultValue: '1:1234567890:web:abcdef123456'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '1234567890'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'recipetools-placeholder'),
    authDomain: 'recipetools-placeholder.firebaseapp.com',
    storageBucket: 'recipetools-placeholder.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY',
        defaultValue: 'AIzaSyPlaceholderAndroidApiKeyForRecipetools'),
    appId: String.fromEnvironment('FIREBASE_ANDROID_APP_ID',
        defaultValue: '1:1234567890:android:abcdef123456'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '1234567890'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'recipetools-placeholder'),
    storageBucket: 'recipetools-placeholder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY',
        defaultValue: 'AIzaSyPlaceholderIosApiKeyForRecipetools'),
    appId: String.fromEnvironment('FIREBASE_IOS_APP_ID',
        defaultValue: '1:1234567890:ios:abcdef123456'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '1234567890'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'recipetools-placeholder'),
    storageBucket: 'recipetools-placeholder.firebasestorage.app',
    iosBundleId: 'com.example.recipetools',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY',
        defaultValue: 'AIzaSyPlaceholderIosApiKeyForRecipetools'),
    appId: String.fromEnvironment('FIREBASE_IOS_APP_ID',
        defaultValue: '1:1234567890:ios:abcdef123456'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '1234567890'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'recipetools-placeholder'),
    storageBucket: 'recipetools-placeholder.firebasestorage.app',
    iosBundleId: 'com.example.recipetools',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WINDOWS_API_KEY',
        defaultValue: 'AIzaSyPlaceholderWindowsApiKey'),
    appId: String.fromEnvironment('FIREBASE_WINDOWS_APP_ID',
        defaultValue: '1:1234567890:web:abcdef123456'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '1234567890'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'recipetools-placeholder'),
    authDomain: 'recipetools-placeholder.firebaseapp.com',
    storageBucket: 'recipetools-placeholder.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_LINUX_API_KEY',
        defaultValue: 'AIzaSyPlaceholderLinuxApiKey'),
    appId: String.fromEnvironment('FIREBASE_LINUX_APP_ID',
        defaultValue: '1:1234567890:web:abcdef123456'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '1234567890'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'recipetools-placeholder'),
    authDomain: 'recipetools-placeholder.firebaseapp.com',
    storageBucket: 'recipetools-placeholder.firebasestorage.app',
  );
}
